spring:
  main:
    banner-mode: off
  application:
    name: spring-database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgpwd4habr
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: 'classpath:db-migration/changelog.xml'